# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Example repro
author: Max Bane <max@thebanes.org>
logo: ""
copyright: 2023, Max Bane

only_build_toc_files: true

execute:
  execute_notebooks: 'cache'
  # execute_notebooks: 'off'

